#! /bin/sh

set -e

cd i18n
msgfmt cs.po -o cs.mo
msgfmt de.po -o de.mo
msgfmt fr.po -o fr.mo
msgfmt pt.po -o pt.mo
msgfmt ru.po -o ru.mo
msgfmt zh.po -o zh.mo
msgfmt es.po -o es.mo
msgfmt nl.po -o nl.mo
