#! /usr/bin/env python

import os
import hashlib
from gettext import GNUTranslations

from django.utils.encoding import smart_str
from jinja2 import Environment, FileSystemLoader

def md5_filter(value):
    return hashlib.md5(value).hexdigest()

env = Environment(loader=FileSystemLoader('templates'),
        extensions=['jinja2.ext.i18n'])
env.install_null_translations()
env.filters["md5"] = md5_filter

templates = [
    "index.html",
    "download.html",
    "docs.html",
    "support.html",
    "screenshots.html",
    "development.html",
    ]

# First generate the English pages:

for template in templates:
    t = env.get_template(template)
    print "Processing '%s'" % template
    name = os.path.splitext(template)[0]
    s = t.render({name + "_active": "active"})
    s = smart_str(s)
    open(template, "w").write(s)

# Now generate the translated pages:

# Setup the i18n:
translations = GNUTranslations(open("i18n/cs.mo"))
env.install_gettext_translations(translations)
print "Generating '%s' translation" % "cs"

for template in templates:
    t = env.get_template(template)
    print "    Processing '%s'" % template
    name = os.path.splitext(template)[0]
    s = t.render({name + "_active": "active"})
    s = smart_str(s)
    open(os.path.join("cs", template), "w").write(s)
